### ISSUE TITLE
下载必要依赖失败

### ISSUE THREAD

**Issue by gonemad4u** [A-Soul-Database/RangeDownloader#1]
进度条不动弹，重开脚本发现以下错误：
File "requests\adapters.py", line 513, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='ghproxy.com', port=443): Max retries exceeded with url: /https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n4.4-latest-win64-lgpl-4.4.zip (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
[32mINFO[0m: 127.0.0.1:4512 - "[1mGET /Install_Progress HTTP/1.1

在此之后是不停的重复以下log
[32mINFO[0m:     127.0.0.1:4747 - "[1mGET /ping HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4782 - "[1mGET /ping HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /ping HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4786 - "[1mGET /ping HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     127.0.0.1:4776 - "[1mGET /Install_Progress HTTP/1.1[0m" [32m200 OK[0m

**Comment by P-PPPP** [comment]
尝试把代理关掉捏

**Comment by P-PPPP** [comment]
可能是你的系统开了代理,导致requests无法解析,尝试关掉代理即可.如果是依赖链接问题可以手动下载ffmpeg即可

**Comment by gonemad4u** [comment]
> 可能是你的系统开了代理,导致requests无法解析,尝试关掉代理即可.如果是依赖链接问题可以手动下载ffmpeg即可

手动下载ffmpeg后能顺利打开，但解析时仍旧报错（vpn已关）：
[31mERROR[0m:    Exception in ASGI application
Traceback (most recent call last):
  File "uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
  File "uvicorn\middleware\proxy_headers.py", line 75, in __call__
  File "uvicorn\middleware\debug.py", line 96, in __call__
  File "uvicorn\middleware\debug.py", line 93, in __call__
  File "fastapi\applications.py", line 208, in __call__
  File "starlette\applications.py", line 112, in __call__
  File "starlette\middleware\errors.py", line 181, in __call__
  File "starlette\middleware\errors.py", line 159, in __call__
  File "starlette\middleware\cors.py", line 92, in __call__
  File "starlette\middleware\cors.py", line 147, in simple_response
  File "starlette\exceptions.py", line 82, in __call__
  File "starlette\exceptions.py", line 71, in __call__
  File "starlette\routing.py", line 656, in __call__
  File "starlette\routing.py", line 259, in handle
  File "starlette\routing.py", line 61, in app
  File "fastapi\routing.py", line 227, in app
  File "fastapi\routing.py", line 161, in run_endpoint_function
  File "starlette\concurrency.py", line 39, in run_in_threadpool
  File "anyio\to_thread.py", line 29, in run_sync
  File "anyio\_backends\_asyncio.py", line 818, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 754, in run
  File "Api\__init__.py", line 51, in Parse
  File "Api\Parser\__init__.py", line 8, in Parse
  File "Api\Parser\BiliBili.py", line 23, in BiliBili
  File "Api\Parser\BiliBili.py", line 38, in get_Info
  File "requests\api.py", line 75, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 529, in request
  File "requests\sessions.py", line 645, in send
  File "requests\adapters.py", line 513, in send

**Comment by gonemad4u** [comment]
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.bilibili.com', port=443): Max retries exceeded with url: /x/web-interface/view?bvid=BV1Wv411N75C (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

反复确认后发现，控制全局的vpn即使把他设置成direct，也会造成无法连接，非得关掉不可……真是有辱程序员身份的问题。
