### ISSUE TITLE
Mac 用户网页报错“下载依赖失败”

### ISSUE THREAD

**Issue by tuteng614** [A-Soul-Database/RangeDownloader#8]
您好，我的Mac OS版本为10.14.6。我下载了最新版源码在python 3.10下成功运行app.py无报错。运行后浏览器自动弹出窗口，网址为https://rd.asdb.live/#mdui-dialog

在“安装”里配置好port（默认的，没有改），输入视频网址后一直卡在“正在解析”这个界面。而命令行中没有任何报错信息，如下所示。
```
INFO:     Started server process [7033]
INFO:     Started server process [7033]
INFO:     Waiting for application startup.
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:4399 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://127.0.0.1:4400 (Press CTRL+C to quit)
服务已启动
```

随后我登陆https://asdb.live/#/./range
在“安装”配置好后不断弹出“连接成功”“下载依赖失败”，以下是命令行中不断弹出的报错信息：
```
INFO:     127.0.0.1:58774 - "GET /Install_FFmpeg HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/teng/VideoProjects/RangeDownloader/Code/ffmpeg_core/__init__.py", line 38, in b
    return Installation.Install_FFmpeg()
  File "/Users/teng/VideoProjects/RangeDownloader/Code/ffmpeg_core/Installation.py", line 36, in Install_FFmpeg
    content_size = int(response.headers['content-length'])
  File "/opt/miniconda3/envs/clip/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

**Comment by tuteng614** [comment]
应该是下载ffmpeg时出了问题？哈哈可能是我这个虚拟环境里没有，我看看自己这解决。

**Comment by tuteng614** [comment]
已经解决！是我这个虚拟环境里没有ffmpeg导致的，运行时程序尝试下载，因此出现问题。

顺便一提，建议注意一下app.py的第35行浏览器默认打开的网址链接
```
32 if Check_Update():
33     webbrowser.open("https://github.com/A-Soul-Database/RangeDownloader/releases/latest")
34 else:
35     webbrowser.open("https://rd.asdb.live")      # 将自动跳转至 https://rd.asdb.live/#mdui-dialog  
          # 此网站在我这里输入视频网址后会一直显示“正在解析”，属于不可用状态
36     # webbrowser.open("https://asdb.live/#/./range") # 这个是可以正常使用的

```
非常感谢您在这个项目上的付出！

**Comment by P-PPPP** [comment]
好的感谢
